// Reference data and clearly marked sample content for local development.

export const COUNTRY = { code: "BD", name: "Bangladesh", currencyCode: "BDT", currencySymbol: "৳", locale: "en-BD", timeZone: "Asia/Dhaka" };

export const CITIES: { slug: string; name: string; lat: number; lng: number; areas: [slug: string, name: string, lat: number, lng: number][] }[] = [
  {
    slug: "dhaka",
    name: "Dhaka",
    lat: 23.8103,
    lng: 90.4125,
    areas: [
      ["gulshan", "Gulshan", 23.7925, 90.4155],
      ["banani", "Banani", 23.7937, 90.4043],
      ["baridhara", "Baridhara", 23.8003, 90.4214],
      ["dhanmondi", "Dhanmondi", 23.7461, 90.3742],
      ["lalmatia", "Lalmatia", 23.7564, 90.37],
      ["mohammadpur", "Mohammadpur", 23.7662, 90.3589],
      ["uttara", "Uttara", 23.8759, 90.3795],
      ["mirpur", "Mirpur", 23.8223, 90.3654],
      ["bashundhara", "Bashundhara R/A", 23.8193, 90.4526],
      ["badda", "Badda", 23.7806, 90.4265],
      ["farmgate", "Farmgate", 23.7577, 90.3897],
      ["motijheel", "Motijheel", 23.733, 90.4172],
      ["tejgaon", "Tejgaon", 23.7639, 90.392],
      ["mohakhali", "Mohakhali", 23.7781, 90.4007],
    ],
  },
  {
    slug: "chattogram",
    name: "Chattogram",
    lat: 22.3569,
    lng: 91.7832,
    areas: [
      ["khulshi", "Khulshi", 22.3614, 91.8056],
      ["agrabad", "Agrabad", 22.3272, 91.812],
      ["nasirabad", "Nasirabad", 22.3669, 91.8235],
      ["gec-circle", "GEC Circle", 22.359, 91.8216],
      ["panchlaish", "Panchlaish", 22.3637, 91.8341],
    ],
  },
  {
    slug: "sylhet",
    name: "Sylhet",
    lat: 24.8949,
    lng: 91.8687,
    areas: [
      ["zindabazar", "Zindabazar", 24.8966, 91.8683],
      ["uposhohor", "Uposhohor", 24.8859, 91.8859],
      ["ambarkhana", "Ambarkhana", 24.9045, 91.8667],
      ["tilagor", "Tilagor", 24.8979, 91.9],
    ],
  },
  {
    slug: "rajshahi",
    name: "Rajshahi",
    lat: 24.3745,
    lng: 88.6042,
    areas: [
      ["shaheb-bazar", "Shaheb Bazar", 24.366, 88.595],
      ["kazla", "Kazla", 24.364, 88.63],
    ],
  },
  {
    slug: "khulna",
    name: "Khulna",
    lat: 22.8456,
    lng: 89.5403,
    areas: [
      ["sonadanga", "Sonadanga", 22.818, 89.548],
      ["khalishpur", "Khalishpur", 22.857, 89.533],
    ],
  },
  {
    slug: "coxs-bazar",
    name: "Cox's Bazar",
    lat: 21.4272,
    lng: 92.0058,
    areas: [["kolatoli", "Kolatoli", 21.421, 92.008]],
  },
];

export const CATEGORIES = [
  { slug: "apartment", name: "Apartment", pluralName: "Apartments", icon: "building-2", description: "Self-contained flats in residential buildings.", usesRoomTypes: false, isCommercial: false },
  { slug: "house", name: "House", pluralName: "Houses", icon: "house", description: "Independent houses and duplexes.", usesRoomTypes: false, isCommercial: false },
  { slug: "single-room", name: "Single room", pluralName: "Single Rooms", icon: "bed-single", description: "A private room in a shared home.", usesRoomTypes: false, isCommercial: false },
  { slug: "shared-room", name: "Shared room", pluralName: "Shared Rooms", icon: "users", description: "Beds in shared rooms, let per bed.", usesRoomTypes: true, isCommercial: false },
  { slug: "hostel", name: "Hostel", pluralName: "Hostels", icon: "bed-double", description: "Managed hostels with dorms and facilities.", usesRoomTypes: true, isCommercial: false },
  { slug: "sublet", name: "Sublet", pluralName: "Sublets", icon: "key-round", description: "Short or fixed-term sublets.", usesRoomTypes: false, isCommercial: false },
  { slug: "commercial", name: "Commercial space", pluralName: "Commercial Spaces", icon: "store", description: "Offices, shops and showrooms.", usesRoomTypes: false, isCommercial: true },
];

export const AMENITIES: { slug: string; name: string; group: "ESSENTIALS" | "BUILDING" | "SAFETY" | "ACCESSIBILITY"; icon: string }[] = [
  { slug: "wifi", name: "Wi-Fi", group: "ESSENTIALS", icon: "wifi" },
  { slug: "air-conditioning", name: "Air conditioning", group: "ESSENTIALS", icon: "snowflake" },
  { slug: "kitchen-access", name: "Kitchen access", group: "ESSENTIALS", icon: "cooking-pot" },
  { slug: "gas-connection", name: "Gas line connection", group: "ESSENTIALS", icon: "flame" },
  { slug: "hot-water", name: "Geyser / hot water", group: "ESSENTIALS", icon: "shower-head" },
  { slug: "washing-machine", name: "Washing machine", group: "ESSENTIALS", icon: "washing-machine" },
  { slug: "balcony", name: "Balcony", group: "ESSENTIALS", icon: "sun" },
  { slug: "meals-included", name: "Meals included", group: "ESSENTIALS", icon: "utensils" },
  { slug: "lift", name: "Lift", group: "BUILDING", icon: "arrow-up-down" },
  { slug: "parking", name: "Car parking", group: "BUILDING", icon: "car" },
  { slug: "backup-electricity", name: "Backup electricity (generator / IPS)", group: "BUILDING", icon: "zap" },
  { slug: "water-24h", name: "24-hour water supply", group: "BUILDING", icon: "droplets" },
  { slug: "rooftop-access", name: "Rooftop access", group: "BUILDING", icon: "building" },
  { slug: "intercom", name: "Intercom", group: "BUILDING", icon: "phone" },
  { slug: "gym", name: "Gym", group: "BUILDING", icon: "dumbbell" },
  { slug: "security", name: "24/7 security guard", group: "SAFETY", icon: "shield-check" },
  { slug: "cctv", name: "CCTV", group: "SAFETY", icon: "cctv" },
  { slug: "fire-safety", name: "Fire extinguishers & exits", group: "SAFETY", icon: "fire-extinguisher" },
  { slug: "step-free-access", name: "Step-free access", group: "ACCESSIBILITY", icon: "accessibility" },
  { slug: "ground-floor", name: "Ground-floor unit", group: "ACCESSIBILITY", icon: "door-open" },
  { slug: "wide-doorways", name: "Wide doorways", group: "ACCESSIBILITY", icon: "move-horizontal" },
  { slug: "accessible-bathroom", name: "Accessible bathroom", group: "ACCESSIBILITY", icon: "bath" },
];

export const DEMO_OWNERS = [
  { key: "farhana", name: "Farhana Rahman", email: "farhana.rahman@example.com", phone: "+880 1711-000101", companyName: "Rahman Property Management", bio: "Sample property manager account. Manages family apartments and houses in Gulshan, Banani and Uttara." },
  { key: "tanvir", name: "Tanvir Ahmed", email: "tanvir.ahmed@example.com", phone: "+880 1811-000202", companyName: null, bio: "Sample individual landlord account with flats in Dhaka, Sylhet and Khulna." },
  { key: "nusrat", name: "Nusrat Jahan", email: "nusrat.jahan@example.com", phone: "+880 1911-000303", companyName: "Green Nest Hostels", bio: "Sample hostel operator account running student and working-women hostels." },
  { key: "imran", name: "Imran Chowdhury", email: "imran.chowdhury@example.com", phone: "+880 1611-000404", companyName: "Chowdhury Commercial Spaces", bio: "Sample commercial landlord account for offices and showrooms in Dhaka and Chattogram." },
] as const;

export const DEMO_TENANTS = [
  { key: "sadia", name: "Sadia Islam", email: "sadia.islam@example.com", phone: "+880 1511-000505", bio: "Sample tenant account." },
  { key: "arif", name: "Arif Hossain", email: "arif.hossain@example.com", phone: "+880 1311-000606", bio: "Sample tenant account." },
] as const;

type Room = { name: string; bedsPerRoom: number; totalBeds: number; availableBeds: number; pricePerBed: number; bathroomType: "PRIVATE" | "SHARED"; description?: string };

export type DemoListing = {
  key: string;
  owner: (typeof DEMO_OWNERS)[number]["key"];
  category: string;
  city: string;
  area: string;
  status?: "PUBLISHED" | "DRAFT" | "PENDING_REVIEW" | "REJECTED" | "RENTED";
  rejectionReason?: string;
  featured?: boolean;
  title: string;
  description: string;
  approximateArea: string;
  addressLine?: string;
  addressVisibility?: "PUBLIC" | "AFTER_ACCEPTED_VIEWING" | "PRIVATE";
  rent?: number;
  period?: "MONTHLY" | "WEEKLY" | "DAILY";
  negotiable?: boolean;
  deposit?: number;
  advanceMonths?: number;
  serviceCharge?: number;
  utilitiesIncluded?: boolean;
  utilitiesNote?: string;
  otherFees?: string;
  bedrooms?: number;
  bathrooms?: number;
  sqft?: number;
  floor?: number;
  totalFloors?: number;
  furnishing?: "FURNISHED" | "SEMI_FURNISHED" | "UNFURNISHED";
  bathroomType?: "PRIVATE" | "SHARED";
  availableInDays: number;
  minimumStay?: number;
  pets?: "ALLOWED" | "NEGOTIABLE" | "NOT_ALLOWED";
  smoking?: boolean;
  preference?: "ANY" | "FAMILY" | "FEMALE_ONLY" | "MALE_ONLY" | "STUDENTS" | "PROFESSIONALS";
  houseRules?: string;
  facilities?: string;
  amenities: string[];
  rooms?: Room[];
  photos: string[];
  publishedDaysAgo: number;
};

export const DEMO_LISTINGS: DemoListing[] = [
  {
    key: "gulshan-3bed",
    owner: "farhana",
    category: "apartment",
    city: "dhaka",
    area: "gulshan",
    featured: true,
    title: "Bright 3-bedroom apartment near Gulshan 2 Circle",
    description:
      "A well-kept 3-bedroom apartment on the 6th floor of a 10-storey building, a short walk from Gulshan 2 Circle. The living and dining area opens onto a wide south-facing balcony, and each bedroom has its own attached bathroom.\n\nThe kitchen has a gas line connection and space for a double-door fridge. The building has two lifts, a full-load generator, underground parking for one car and round-the-clock security.",
    approximateArea: "Near Gulshan 2 Circle",
    addressLine: "House 12, Road 45, Gulshan 2, Dhaka 1212",
    addressVisibility: "AFTER_ACCEPTED_VIEWING",
    rent: 85000,
    serviceCharge: 8000,
    deposit: 170000,
    advanceMonths: 2,
    utilitiesNote: "Electricity (prepaid meter) and gas bills are paid by the tenant.",
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1850,
    floor: 6,
    totalFloors: 10,
    furnishing: "SEMI_FURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 14,
    minimumStay: 12,
    preference: "FAMILY",
    houseRules: "Families preferred.\nNo commercial use.\nVisitors must register with building security after 10 pm.",
    amenities: ["lift", "parking", "backup-electricity", "security", "cctv", "gas-connection", "water-24h", "intercom", "balcony", "hot-water"],
    photos: ["living-1", "kitchen-1", "bedroom-1", "bathroom-1", "building-1"],
    publishedDaysAgo: 2,
  },
  {
    key: "banani-serviced",
    owner: "farhana",
    category: "apartment",
    city: "dhaka",
    area: "banani",
    featured: true,
    title: "Furnished 2-bedroom serviced apartment in Banani",
    description:
      "Fully furnished 2-bedroom apartment in a quiet lane off Banani Road 11, ideal for professionals or small families relocating to Dhaka. Comes with air conditioning in every room, a fitted kitchen, washing machine and high-speed Wi-Fi.\n\nWeekly housekeeping is included in the service charge. Restaurants, supermarkets and the Banani lake park are within walking distance.",
    approximateArea: "Off Banani Road 11",
    addressVisibility: "PRIVATE",
    rent: 120000,
    serviceCharge: 12000,
    deposit: 240000,
    advanceMonths: 1,
    utilitiesIncluded: true,
    utilitiesNote: "Wi-Fi, water and gas included. Electricity billed on actual usage.",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1350,
    floor: 4,
    totalFloors: 9,
    furnishing: "FURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 0,
    minimumStay: 6,
    preference: "PROFESSIONALS",
    pets: "NEGOTIABLE",
    amenities: ["wifi", "air-conditioning", "lift", "backup-electricity", "security", "cctv", "washing-machine", "hot-water", "gym", "parking"],
    photos: ["living-2", "bedroom-2", "kitchen-2", "dining-1", "bathroom-2"],
    publishedDaysAgo: 5,
  },
  {
    key: "dhanmondi-family",
    owner: "tanvir",
    category: "apartment",
    city: "dhaka",
    area: "dhanmondi",
    title: "Family flat near Dhanmondi Lake with 3 bedrooms",
    description:
      "Spacious unfurnished 3-bedroom flat on the 3rd floor, two minutes from Dhanmondi Lake. Large windows keep the rooms bright and airy. There are two attached bathrooms and one common bathroom, plus a separate servant's room.\n\nSchools, hospitals and Rapa Plaza are close by. The building has a lift and generator backup for lights and fans.",
    approximateArea: "Road 8A, near Dhanmondi Lake",
    rent: 45000,
    serviceCharge: 3500,
    deposit: 90000,
    advanceMonths: 2,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1600,
    floor: 3,
    totalFloors: 7,
    furnishing: "UNFURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 20,
    minimumStay: 12,
    preference: "FAMILY",
    houseRules: "Family only.\nNo smoking inside the building.",
    amenities: ["lift", "backup-electricity", "gas-connection", "security", "water-24h", "balcony"],
    photos: ["living-3", "bedroom-3", "kitchen-3", "building-2"],
    publishedDaysAgo: 9,
  },
  {
    key: "uttara-4bed",
    owner: "farhana",
    category: "apartment",
    city: "dhaka",
    area: "uttara",
    title: "Spacious 4-bedroom apartment in Uttara Sector 7",
    description:
      "A large 4-bedroom apartment with a separate drawing and dining room, close to Uttara Sector 7 park and the Airport Road. Suitable for a large family. Tiles throughout, wardrobes in two bedrooms, and a covered car parking space.\n\nThe metro rail station at Uttara Centre is about 10 minutes away by rickshaw.",
    approximateArea: "Sector 7, near the park",
    rent: 38000,
    serviceCharge: 3000,
    deposit: 76000,
    advanceMonths: 2,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2100,
    floor: 5,
    totalFloors: 8,
    furnishing: "SEMI_FURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 30,
    minimumStay: 12,
    preference: "FAMILY",
    pets: "NEGOTIABLE",
    amenities: ["lift", "parking", "backup-electricity", "gas-connection", "security", "rooftop-access"],
    photos: ["living-4", "dining-2", "bedroom-4", "building-3"],
    publishedDaysAgo: 12,
  },
  {
    key: "mirpur-2bed",
    owner: "tanvir",
    category: "apartment",
    city: "dhaka",
    area: "mirpur",
    title: "Affordable 2-bedroom flat in Mirpur 10",
    description:
      "Budget-friendly 2-bedroom flat on the 2nd floor, a 5-minute walk from Mirpur 10 metro station. One attached and one common bathroom, a small balcony and a kitchen with gas line connection.\n\nThere is no lift in this 5-storey walk-up building. Suitable for a small family or two working professionals.",
    approximateArea: "Near Mirpur 10 metro station",
    rent: 18000,
    serviceCharge: 1000,
    deposit: 18000,
    advanceMonths: 1,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 850,
    floor: 2,
    totalFloors: 5,
    furnishing: "UNFURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 0,
    minimumStay: 6,
    amenities: ["gas-connection", "balcony", "water-24h"],
    photos: ["living-5", "bedroom-5", "kitchen-4"],
    publishedDaysAgo: 1,
  },
  {
    key: "bashundhara-3bed",
    owner: "farhana",
    category: "apartment",
    city: "dhaka",
    area: "bashundhara",
    title: "Modern 3-bedroom apartment near NSU, Bashundhara",
    description:
      "Newly built 3-bedroom apartment in Block D, Bashundhara R/A, a few minutes from North South University and Apollo Hospital. Features modern bathroom fittings, an open kitchen and a large balcony.\n\nThe building has step-free entry from the street, a lift large enough for a wheelchair, CCTV and a full-time guard.",
    approximateArea: "Block D, near North South University",
    addressLine: "Road 7, Block D, Bashundhara R/A, Dhaka",
    addressVisibility: "PUBLIC",
    rent: 32000,
    serviceCharge: 2500,
    deposit: 64000,
    advanceMonths: 2,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1450,
    floor: 1,
    totalFloors: 9,
    furnishing: "SEMI_FURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 7,
    minimumStay: 12,
    amenities: ["lift", "backup-electricity", "security", "cctv", "step-free-access", "wide-doorways", "gas-connection", "balcony"],
    photos: ["living-6", "bedroom-6", "bathroom-3", "building-4"],
    publishedDaysAgo: 3,
  },
  {
    key: "baridhara-duplex",
    owner: "farhana",
    category: "house",
    city: "dhaka",
    area: "baridhara",
    featured: true,
    title: "Duplex house with garden in Baridhara",
    description:
      "An elegant 5-bedroom duplex with a private front garden and parking for three cars in the Baridhara diplomatic area. The ground floor has a double-height living room, formal dining, a family lounge and a guest bedroom; the upper floor has four en-suite bedrooms.\n\nFully furnished with air conditioning, generator backup and dedicated security. Pets are welcome.",
    approximateArea: "Baridhara diplomatic zone",
    addressVisibility: "PRIVATE",
    rent: 350000,
    serviceCharge: 0,
    deposit: 1050000,
    advanceMonths: 3,
    utilitiesNote: "All utility bills paid by the tenant. Gardener's salary included in rent.",
    bedrooms: 5,
    bathrooms: 6,
    sqft: 5200,
    totalFloors: 2,
    furnishing: "FURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 45,
    minimumStay: 24,
    pets: "ALLOWED",
    preference: "FAMILY",
    amenities: ["air-conditioning", "parking", "backup-electricity", "security", "cctv", "gas-connection", "hot-water", "washing-machine", "ground-floor", "rooftop-access"],
    photos: ["house-1", "living-7", "dining-1", "bedroom-7", "kitchen-1"],
    publishedDaysAgo: 7,
  },
  {
    key: "uttara-house",
    owner: "tanvir",
    category: "house",
    city: "dhaka",
    area: "uttara",
    title: "Three-storey family house in Uttara Sector 13",
    description:
      "Independent three-storey house on a quiet residential road in Uttara Sector 13 with 4 bedrooms, a roof terrace and a small courtyard. The ground floor has step-free access and a bedroom with an accessible bathroom, suitable for an elderly family member.\n\nClose to schools, Sector 13 lake and Rajlakshmi shopping area.",
    approximateArea: "Sector 13, near the lake",
    rent: 95000,
    deposit: 190000,
    advanceMonths: 2,
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3200,
    totalFloors: 3,
    furnishing: "UNFURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 25,
    minimumStay: 12,
    pets: "ALLOWED",
    preference: "FAMILY",
    amenities: ["parking", "gas-connection", "rooftop-access", "step-free-access", "ground-floor", "accessible-bathroom", "security"],
    photos: ["house-2", "living-8", "bedroom-1", "bathroom-1"],
    publishedDaysAgo: 15,
  },
  {
    key: "mohammadpur-women-room",
    owner: "tanvir",
    category: "single-room",
    city: "dhaka",
    area: "mohammadpur",
    title: "Single room with attached bath for working women",
    description:
      "A furnished single room with an attached bathroom in a family apartment in Mohammadpur, near Asad Gate. The room has a bed, wardrobe, study table and a ceiling fan. Kitchen access is shared with one other tenant.\n\nWi-Fi and utility bills are included. Suitable for a working woman or female postgraduate student.",
    approximateArea: "Near Asad Gate",
    rent: 9500,
    deposit: 9500,
    utilitiesIncluded: true,
    utilitiesNote: "Electricity, gas, water and Wi-Fi included.",
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "FURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 3,
    minimumStay: 3,
    preference: "FEMALE_ONLY",
    houseRules: "Women only.\nMain gate closes at 10:30 pm.\nNo overnight guests.",
    amenities: ["wifi", "kitchen-access", "gas-connection", "security"],
    photos: ["bedroom-2", "bathroom-2", "kitchen-2"],
    publishedDaysAgo: 4,
  },
  {
    key: "badda-room",
    owner: "tanvir",
    category: "single-room",
    city: "dhaka",
    area: "badda",
    title: "Furnished single room near Gulshan–Badda Link Road",
    description:
      "Bright single room with a large window in a shared 3-bedroom flat near the Gulshan–Badda Link Road. Shared bathroom with one other person, shared kitchen and a common balcony.\n\nIdeal for young professionals working in Gulshan or Tejgaon. Bills are split equally between flatmates.",
    approximateArea: "Near Gulshan–Badda Link Road",
    rent: 8000,
    deposit: 8000,
    utilitiesNote: "Bills split equally between three flatmates (about ৳1,200/month each).",
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "FURNISHED",
    bathroomType: "SHARED",
    availableInDays: 10,
    minimumStay: 6,
    preference: "MALE_ONLY",
    amenities: ["wifi", "kitchen-access", "balcony", "washing-machine"],
    photos: ["bedroom-3", "living-9", "kitchen-3"],
    publishedDaysAgo: 6,
  },
  {
    key: "farmgate-shared",
    owner: "nusrat",
    category: "shared-room",
    city: "dhaka",
    area: "farmgate",
    title: "Shared rooms for male students near Farmgate",
    description:
      "Clean and well-managed shared accommodation (mess) for male students, a short walk from Farmgate and the coaching centres of Green Road. Each bed comes with a mattress, locker and study space. Rooms are cleaned daily.\n\nTwo meals a day are available at extra cost. Quiet hours after 11 pm.",
    approximateArea: "Near Farmgate bus stand",
    period: "MONTHLY",
    deposit: 3000,
    utilitiesIncluded: true,
    utilitiesNote: "Electricity, water and Wi-Fi included in the bed rent.",
    bathrooms: 3,
    availableInDays: 0,
    minimumStay: 3,
    preference: "STUDENTS",
    houseRules: "Male students only.\nNo smoking.\nQuiet hours 11 pm – 7 am.",
    facilities: "Daily room cleaning, lockers, study tables, shared kitchen, optional meal plan (৳3,500/month).",
    amenities: ["wifi", "kitchen-access", "backup-electricity", "security", "water-24h"],
    rooms: [
      { name: "Twin sharing room", bedsPerRoom: 2, totalBeds: 6, availableBeds: 1, pricePerBed: 5500, bathroomType: "SHARED" },
      { name: "Three-bed room", bedsPerRoom: 3, totalBeds: 12, availableBeds: 4, pricePerBed: 4200, bathroomType: "SHARED" },
    ],
    photos: ["dorm-2", "bedroom-4", "kitchen-4"],
    publishedDaysAgo: 8,
  },
  {
    key: "lalmatia-women-hostel",
    owner: "nusrat",
    category: "hostel",
    city: "dhaka",
    area: "lalmatia",
    featured: true,
    title: "Green Nest Women's Hostel, Lalmatia",
    description:
      "A safe, friendly hostel for female students and working women in Lalmatia, close to Dhanmondi and Asad Gate. Choose from 4-bed dorms, twin rooms or private single rooms.\n\nThree home-cooked meals a day, laundry service, a reading room and a female warden on site. CCTV at every entrance and a 24/7 guard.",
    approximateArea: "Block D, Lalmatia",
    addressLine: "House 5/7, Block D, Lalmatia, Dhaka 1207",
    addressVisibility: "PUBLIC",
    period: "MONTHLY",
    deposit: 5000,
    utilitiesIncluded: true,
    utilitiesNote: "All utilities, Wi-Fi and three meals included.",
    bathrooms: 8,
    availableInDays: 0,
    minimumStay: 3,
    preference: "FEMALE_ONLY",
    houseRules: "Women only.\nEntry closes at 10 pm (later with prior notice for night shifts).\nNo male visitors beyond the reception.",
    facilities: "Three meals daily, weekly laundry, reading room, rooftop garden, female warden, first-aid kit.",
    amenities: ["wifi", "meals-included", "security", "cctv", "backup-electricity", "water-24h", "hot-water", "rooftop-access", "fire-safety"],
    rooms: [
      { name: "4-bed dorm", bedsPerRoom: 4, totalBeds: 16, availableBeds: 5, pricePerBed: 4500, bathroomType: "SHARED", description: "Bunk beds with personal lockers and reading lamps." },
      { name: "Twin room", bedsPerRoom: 2, totalBeds: 8, availableBeds: 2, pricePerBed: 7000, bathroomType: "SHARED" },
      { name: "Private single room", bedsPerRoom: 1, totalBeds: 4, availableBeds: 0, pricePerBed: 11000, bathroomType: "PRIVATE", description: "Attached bathroom and air conditioning." },
    ],
    photos: ["dorm-1", "bedroom-5", "dining-2", "living-10"],
    publishedDaysAgo: 10,
  },
  {
    key: "mirpur-hostel",
    owner: "nusrat",
    category: "hostel",
    city: "dhaka",
    area: "mirpur",
    title: "Mirpur professionals' hostel with meals",
    description:
      "A hostel for working men in Mirpur 2, near the stadium and Mirpur 10 metro station. Rooms are air-conditioned, with a shared lounge, TV room and a dining hall serving breakfast and dinner.\n\nFlexible monthly stays; a good option while you look for a long-term flat.",
    approximateArea: "Mirpur 2, near the stadium",
    period: "MONTHLY",
    deposit: 4000,
    utilitiesIncluded: true,
    bathrooms: 6,
    availableInDays: 0,
    minimumStay: 1,
    preference: "PROFESSIONALS",
    houseRules: "Men only.\nNo smoking indoors.\nVisitors allowed in the lounge until 9 pm.",
    facilities: "Breakfast and dinner, laundry room, TV lounge, rooftop.",
    amenities: ["wifi", "air-conditioning", "meals-included", "security", "backup-electricity", "washing-machine", "lift"],
    rooms: [
      { name: "3-bed AC room", bedsPerRoom: 3, totalBeds: 18, availableBeds: 6, pricePerBed: 6500, bathroomType: "SHARED" },
      { name: "Twin AC room", bedsPerRoom: 2, totalBeds: 10, availableBeds: 3, pricePerBed: 8500, bathroomType: "PRIVATE" },
    ],
    photos: ["dorm-2", "bedroom-6", "living-11"],
    publishedDaysAgo: 11,
  },
  {
    key: "banani-studio-sublet",
    owner: "farhana",
    category: "sublet",
    city: "dhaka",
    area: "banani",
    title: "Furnished studio sublet in Banani, weekly rent",
    description:
      "A cosy furnished studio available as a sublet for 1–3 months while the leaseholder is abroad. Includes a double bed, sofa, kitchenette, air conditioning and fast Wi-Fi.\n\nWeekly rent covers utilities and housekeeping once a week. Great for consultants and visiting researchers.",
    approximateArea: "Banani Road 17",
    rent: 14000,
    period: "WEEKLY",
    deposit: 14000,
    utilitiesIncluded: true,
    utilitiesNote: "All utilities and Wi-Fi included.",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 550,
    floor: 7,
    totalFloors: 12,
    furnishing: "FURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 5,
    minimumStay: 4,
    amenities: ["wifi", "air-conditioning", "lift", "backup-electricity", "security", "hot-water"],
    photos: ["living-12", "bedroom-7", "kitchen-1"],
    publishedDaysAgo: 2,
  },
  {
    key: "motijheel-office",
    owner: "imran",
    category: "commercial",
    city: "dhaka",
    area: "motijheel",
    title: "2,400 sq ft office floor in Motijheel commercial area",
    description:
      "An open-plan office floor on the 9th floor of a commercial tower in Motijheel C/A, close to Bangladesh Bank and major bank head offices. Comes with two washrooms, a pantry and a glass-partitioned meeting room.\n\nThe building has three lifts, a full-load generator, step-free entry and 24/7 security.",
    approximateArea: "Motijheel C/A",
    rent: 180000,
    serviceCharge: 24000,
    deposit: 540000,
    advanceMonths: 3,
    otherFees: "VAT applicable as per government rules.",
    bathrooms: 2,
    sqft: 2400,
    floor: 9,
    totalFloors: 15,
    furnishing: "SEMI_FURNISHED",
    availableInDays: 30,
    minimumStay: 24,
    amenities: ["lift", "backup-electricity", "security", "cctv", "fire-safety", "step-free-access", "air-conditioning", "parking"],
    photos: ["office-3", "office-2", "office-4"],
    publishedDaysAgo: 14,
  },
  {
    key: "tejgaon-showroom",
    owner: "imran",
    category: "commercial",
    city: "dhaka",
    area: "tejgaon",
    title: "Ground-floor showroom on Tejgaon–Gulshan Link Road",
    description:
      "High-visibility ground-floor showroom with a 40 ft glass frontage on the Tejgaon–Gulshan Link Road. Suitable for furniture, electronics, car accessories or a café. Includes a mezzanine storage area and a rear loading entrance.",
    approximateArea: "Tejgaon–Gulshan Link Road",
    rent: 250000,
    serviceCharge: 15000,
    deposit: 750000,
    advanceMonths: 3,
    bathrooms: 1,
    sqft: 3000,
    floor: 0,
    totalFloors: 6,
    furnishing: "UNFURNISHED",
    availableInDays: 60,
    minimumStay: 36,
    amenities: ["backup-electricity", "security", "cctv", "ground-floor", "step-free-access", "parking", "fire-safety"],
    photos: ["shop-1", "empty-1", "cafe-1"],
    publishedDaysAgo: 20,
  },
  {
    key: "khulshi-3bed",
    owner: "imran",
    category: "apartment",
    city: "chattogram",
    area: "khulshi",
    title: "Hillside 3-bedroom apartment in Khulshi",
    description:
      "A peaceful 3-bedroom apartment in the green hills of Khulshi with views over the city. Large balcony, separate dining space and a modern kitchen. Close to Khulshi Town Centre and several international schools.\n\nLift, generator and a guarded parking area.",
    approximateArea: "Khulshi Hills",
    rent: 40000,
    serviceCharge: 3000,
    deposit: 80000,
    advanceMonths: 2,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1700,
    floor: 5,
    totalFloors: 8,
    furnishing: "SEMI_FURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 15,
    minimumStay: 12,
    preference: "FAMILY",
    pets: "NEGOTIABLE",
    amenities: ["lift", "parking", "backup-electricity", "security", "gas-connection", "balcony", "hot-water"],
    photos: ["living-13", "bedroom-1", "kitchen-2", "building-1"],
    publishedDaysAgo: 6,
  },
  {
    key: "agrabad-2bed",
    owner: "imran",
    category: "apartment",
    city: "chattogram",
    area: "agrabad",
    title: "2-bedroom apartment near Agrabad commercial area",
    description:
      "Convenient 2-bedroom apartment within walking distance of Agrabad's banks and offices. Tiled floors, two bathrooms and a balcony. Good public transport links to the port and GEC Circle.",
    approximateArea: "Near Agrabad Access Road",
    rent: 22000,
    serviceCharge: 1500,
    deposit: 44000,
    advanceMonths: 2,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1050,
    floor: 4,
    totalFloors: 6,
    furnishing: "UNFURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 0,
    minimumStay: 12,
    amenities: ["gas-connection", "balcony", "backup-electricity", "water-24h"],
    photos: ["living-14", "bedroom-2", "bathroom-3"],
    publishedDaysAgo: 18,
  },
  {
    key: "agrabad-office",
    owner: "imran",
    category: "commercial",
    city: "chattogram",
    area: "agrabad",
    title: "Office suite in Agrabad with generator backup",
    description:
      "A ready-to-use 1,200 sq ft office suite with four cabins, an open workstation area and a reception. Located in a well-maintained commercial building in Agrabad C/A with lifts and a full-load generator.",
    approximateArea: "Agrabad C/A",
    rent: 90000,
    serviceCharge: 10000,
    deposit: 270000,
    advanceMonths: 3,
    bathrooms: 2,
    sqft: 1200,
    floor: 6,
    totalFloors: 12,
    furnishing: "FURNISHED",
    availableInDays: 10,
    minimumStay: 12,
    amenities: ["lift", "backup-electricity", "air-conditioning", "security", "cctv", "wifi", "fire-safety"],
    photos: ["office-1", "office-2", "office-3"],
    publishedDaysAgo: 22,
  },
  {
    key: "gec-student-mess",
    owner: "nusrat",
    category: "shared-room",
    city: "chattogram",
    area: "gec-circle",
    title: "Student mess near GEC Circle, Chattogram",
    description:
      "Shared rooms for male university students near GEC Circle, with easy access to Chittagong College and coaching centres. Meals are cooked by a resident cook and billed separately each month.",
    approximateArea: "Near GEC Circle",
    period: "MONTHLY",
    deposit: 2000,
    utilitiesIncluded: true,
    bathrooms: 2,
    availableInDays: 0,
    minimumStay: 3,
    preference: "STUDENTS",
    houseRules: "Male students only.\nNo smoking.\nShare cleaning duties as per the weekly roster.",
    facilities: "Resident cook (meal bill shared), Wi-Fi, study tables.",
    amenities: ["wifi", "kitchen-access", "water-24h"],
    rooms: [{ name: "Four-bed room", bedsPerRoom: 4, totalBeds: 12, availableBeds: 3, pricePerBed: 3200, bathroomType: "SHARED" }],
    photos: ["dorm-1", "bedroom-3"],
    publishedDaysAgo: 16,
  },
  {
    key: "sylhet-house",
    owner: "tanvir",
    category: "house",
    city: "sylhet",
    area: "uposhohor",
    title: "Independent house with courtyard in Uposhohor, Sylhet",
    description:
      "A two-storey independent house with 4 bedrooms and a paved courtyard in Uposhohor, Sylhet. Quiet neighbourhood with a mosque, school and market nearby. Parking for one car inside the gate.",
    approximateArea: "Uposhohor Block B",
    rent: 35000,
    deposit: 70000,
    advanceMonths: 2,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2400,
    totalFloors: 2,
    furnishing: "UNFURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 21,
    minimumStay: 12,
    pets: "ALLOWED",
    preference: "FAMILY",
    amenities: ["parking", "gas-connection", "ground-floor", "rooftop-access", "water-24h"],
    photos: ["house-3", "living-15", "bedroom-4"],
    publishedDaysAgo: 13,
  },
  {
    key: "zindabazar-furnished",
    owner: "tanvir",
    category: "apartment",
    city: "sylhet",
    area: "zindabazar",
    title: "Furnished 2-bedroom apartment in Zindabazar",
    description:
      "Centrally located furnished apartment in Zindabazar, walking distance to shopping malls, restaurants and Sylhet's main business area. Comes with beds, sofa set, dining table, fridge and air conditioning in the master bedroom.",
    approximateArea: "Zindabazar Point",
    rent: 20000,
    serviceCharge: 1500,
    deposit: 40000,
    advanceMonths: 1,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1000,
    floor: 3,
    totalFloors: 6,
    furnishing: "FURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 0,
    minimumStay: 6,
    amenities: ["air-conditioning", "lift", "backup-electricity", "gas-connection", "security"],
    photos: ["living-16", "bedroom-5", "kitchen-3"],
    publishedDaysAgo: 5,
  },
  {
    key: "ambarkhana-room",
    owner: "tanvir",
    category: "single-room",
    city: "sylhet",
    area: "ambarkhana",
    title: "Single room for rent near Ambarkhana",
    description:
      "Simple single room with a shared bathroom in a family house near Ambarkhana point. Suitable for a student or a working professional. Meals can be arranged with the family on request.",
    approximateArea: "Ambarkhana point",
    rent: 6000,
    deposit: 6000,
    utilitiesIncluded: true,
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "SEMI_FURNISHED",
    bathroomType: "SHARED",
    availableInDays: 7,
    minimumStay: 3,
    amenities: ["wifi", "water-24h"],
    photos: ["bedroom-6", "bathroom-1"],
    publishedDaysAgo: 3,
  },
  {
    key: "rajshahi-university-hostel",
    owner: "nusrat",
    category: "hostel",
    city: "rajshahi",
    area: "kazla",
    title: "Student hostel near Rajshahi University, Kazla",
    description:
      "Affordable, quiet student hostel in Kazla, a short walk from the Rajshahi University main gate. Twin and four-bed rooms with study tables, a common dining hall and reliable Wi-Fi.",
    approximateArea: "Kazla, near RU main gate",
    period: "MONTHLY",
    deposit: 2500,
    utilitiesIncluded: true,
    bathrooms: 4,
    availableInDays: 0,
    minimumStay: 6,
    preference: "STUDENTS",
    houseRules: "Students only.\nGate closes at 11 pm.",
    facilities: "Dining hall (meal plan optional), Wi-Fi, study room, water filter.",
    amenities: ["wifi", "security", "backup-electricity", "water-24h", "kitchen-access"],
    rooms: [
      { name: "Twin room", bedsPerRoom: 2, totalBeds: 20, availableBeds: 4, pricePerBed: 3000, bathroomType: "SHARED" },
      { name: "Four-bed room", bedsPerRoom: 4, totalBeds: 24, availableBeds: 7, pricePerBed: 2200, bathroomType: "SHARED" },
    ],
    photos: ["dorm-2", "bedroom-7", "dining-1"],
    publishedDaysAgo: 9,
  },
  {
    key: "khulna-sonadanga",
    owner: "tanvir",
    category: "apartment",
    city: "khulna",
    area: "sonadanga",
    title: "Family apartment in Sonadanga R/A, Khulna",
    description:
      "A comfortable 3-bedroom family apartment in Sonadanga Residential Area, near the bus terminal and Khulna Medical College road. Includes a separate drawing room, two bathrooms and a balcony facing a quiet street.",
    approximateArea: "Sonadanga R/A, Phase 2",
    rent: 16000,
    serviceCharge: 800,
    deposit: 32000,
    advanceMonths: 2,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1250,
    floor: 2,
    totalFloors: 5,
    furnishing: "UNFURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 12,
    minimumStay: 12,
    preference: "FAMILY",
    amenities: ["gas-connection", "balcony", "water-24h", "rooftop-access"],
    photos: ["living-17", "bedroom-1", "kitchen-4"],
    publishedDaysAgo: 17,
  },
  {
    key: "coxs-bazar-daily",
    owner: "farhana",
    category: "sublet",
    city: "coxs-bazar",
    area: "kolatoli",
    title: "Sea-view furnished flat in Kolatoli, daily rent",
    description:
      "A fully furnished 2-bedroom flat a short walk from Kolatoli beach, available by the day. Two air-conditioned bedrooms, a living room with a sea-facing balcony and a kitchen with basic utensils. Suitable for families on holiday.",
    approximateArea: "Kolatoli, near the beach",
    rent: 3500,
    period: "DAILY",
    deposit: 3500,
    utilitiesIncluded: true,
    utilitiesNote: "Electricity, water, gas and Wi-Fi included.",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    floor: 5,
    totalFloors: 8,
    furnishing: "FURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 0,
    minimumStay: 2,
    preference: "FAMILY",
    houseRules: "Check-in after 12 pm, check-out by 11 am.\nNo parties.",
    amenities: ["wifi", "air-conditioning", "lift", "backup-electricity", "balcony", "hot-water", "kitchen-access"],
    photos: ["living-18", "bedroom-2", "living-19"],
    publishedDaysAgo: 1,
  },
  // ─── Non-published examples for the owner and admin dashboards ───
  {
    key: "bashundhara-pending",
    owner: "farhana",
    category: "apartment",
    city: "dhaka",
    area: "bashundhara",
    status: "PENDING_REVIEW",
    title: "New 2-bedroom apartment in Bashundhara Block C",
    description:
      "Brand-new 2-bedroom apartment in Block C with an open kitchen, two bathrooms and a balcony overlooking the lake. Lift, generator and security. Waiting for approval before it goes live.",
    approximateArea: "Block C, near the lake",
    rent: 26000,
    serviceCharge: 2000,
    deposit: 52000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    floor: 6,
    totalFloors: 9,
    furnishing: "UNFURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 20,
    minimumStay: 12,
    amenities: ["lift", "backup-electricity", "security", "gas-connection", "balcony"],
    photos: ["living-20", "bedroom-3", "kitchen-2"],
    publishedDaysAgo: 0,
  },
  {
    key: "mohakhali-draft",
    owner: "tanvir",
    category: "apartment",
    city: "dhaka",
    area: "mohakhali",
    status: "DRAFT",
    title: "2-bedroom flat in Mohakhali DOHS",
    description: "Draft listing — photos and pricing still to be added.",
    approximateArea: "Mohakhali DOHS",
    bedrooms: 2,
    bathrooms: 2,
    availableInDays: 30,
    amenities: ["lift"],
    photos: [],
    publishedDaysAgo: 0,
  },
  {
    key: "tilagor-rejected",
    owner: "tanvir",
    category: "single-room",
    city: "sylhet",
    area: "tilagor",
    status: "REJECTED",
    rejectionReason: "Please replace the photos with pictures of the actual room and add details about the bathroom.",
    title: "Room available in Tilagor for students",
    description: "A room for a student in Tilagor near Shahjalal University of Science and Technology. Contact for details about the bathroom and meals.",
    approximateArea: "Tilagor",
    rent: 5000,
    furnishing: "SEMI_FURNISHED",
    availableInDays: 5,
    amenities: ["wifi"],
    photos: ["bedroom-4", "living-1", "kitchen-1"],
    publishedDaysAgo: 0,
  },
  {
    key: "gulshan-rented",
    owner: "farhana",
    category: "apartment",
    city: "dhaka",
    area: "gulshan",
    status: "RENTED",
    title: "Lake-view 3-bedroom apartment in Gulshan 1",
    description: "A 3-bedroom lake-view apartment in Gulshan 1 that has recently been rented. Kept for the owner's records and can be relisted when it becomes vacant again.",
    approximateArea: "Gulshan 1, near the lake",
    rent: 110000,
    serviceCharge: 10000,
    deposit: 220000,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2000,
    furnishing: "SEMI_FURNISHED",
    bathroomType: "PRIVATE",
    availableInDays: 90,
    amenities: ["lift", "parking", "backup-electricity", "security"],
    photos: ["living-3", "bedroom-5", "building-2"],
    publishedDaysAgo: 40,
  },
];
