import {
  Accessibility,
  AirVent,
  ArrowUpDown,
  Bath,
  BatteryCharging,
  BedDouble,
  BedSingle,
  Bike,
  Briefcase,
  Building,
  Building2,
  Car,
  Cctv,
  Check,
  CookingPot,
  Dog,
  DoorOpen,
  Droplets,
  Dumbbell,
  Fan,
  FireExtinguisher,
  Flame,
  Hotel,
  House,
  KeyRound,
  Landmark,
  Lock,
  MoveHorizontal,
  Phone,
  Refrigerator,
  School,
  ShieldCheck,
  ShowerHead,
  Sofa,
  Store,
  Sun,
  Trees,
  Tv,
  Users,
  Utensils,
  Warehouse,
  WashingMachine,
  Waves,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Icons that admins can assign to categories and amenities (stored by name in the database). */
export const ICONS: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  "air-vent": AirVent,
  "arrow-up-down": ArrowUpDown,
  bath: Bath,
  "battery-charging": BatteryCharging,
  "bed-double": BedDouble,
  "bed-single": BedSingle,
  bike: Bike,
  briefcase: Briefcase,
  building: Building,
  "building-2": Building2,
  car: Car,
  cctv: Cctv,
  check: Check,
  "cooking-pot": CookingPot,
  dog: Dog,
  "door-open": DoorOpen,
  droplets: Droplets,
  dumbbell: Dumbbell,
  fan: Fan,
  "fire-extinguisher": FireExtinguisher,
  flame: Flame,
  hotel: Hotel,
  house: House,
  "key-round": KeyRound,
  landmark: Landmark,
  lock: Lock,
  "move-horizontal": MoveHorizontal,
  phone: Phone,
  refrigerator: Refrigerator,
  school: School,
  "shield-check": ShieldCheck,
  "shower-head": ShowerHead,
  sofa: Sofa,
  store: Store,
  sun: Sun,
  trees: Trees,
  tv: Tv,
  users: Users,
  utensils: Utensils,
  warehouse: Warehouse,
  "washing-machine": WashingMachine,
  waves: Waves,
  wifi: Wifi,
  zap: Zap,
};

export const ICON_NAMES = Object.keys(ICONS).sort();

export function NamedIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? Check;
  return <Icon className={className} aria-hidden="true" />;
}
